In [1]:
import numpy as np
temp=np.array([34,39,18,34,31,100,34,30,37])
mean=np.mean(temp)
std=np.std(temp)
print(mean)

39.666666666666664

In [2]:
print(std)

22.065558884580486

In [3]:
nor=(temp-mean)/std
nor

array([-0.25681048, -0.030213  , -0.98192241, -0.25681048, -0.39276896,
        2.73427624, -0.25681048, -0.43808846, -0.12085199])

In [4]:
temp[np.abs(nor)>2]

array([100])

In [5]:
a=np.array([12,34,5,67,89])
b=np.array([243,67,89,90,78])
c=a-b
print(c)

[-231  -33  -84  -23   11]

In [6]:
x=np.array([5,3])
y=np.array([2,1])
dis=np.sqrt(np.sum((x-y)**2))
print(dis)

3.605551275463989

In [8]:
sales=[200,250,320,400,380,200,270]
changes=np.diff(sales)
changes/sales[:-1]

array([ 0.25      ,  0.28      ,  0.25      , -0.05      , -0.47368421,
        0.35      ])

In [9]:
marks=np.array([90,89,67,32,56,49,58,78])
mean=np.mean(marks)
mean

64.875

In [12]:
np.where(marks<mean)

(array([3, 4, 5, 6], dtype=int64),)

In [14]:
marks=np.array([90,89,67,np.NaN,32,56,49,58,78,np.NaN])
marks

array([90., 89., 67., nan, 32., 56., 49., 58., 78., nan])

In [15]:
np.mean(marks)

nan

In [23]:
np.where(np.isnan(marks),0,marks)

array([90., 89., 67.,  0., 32., 56., 49., 58., 78.,  0.])

In [24]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\admin\appdata\roaming\python\python310\site-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
import pandas as pd
s=pd.Series(["shalini","atul","amit","naman"],index=
           [101,109,104,102])
print(s[104])

amit

In [28]:
dic={"101":"shalini sharma","102":"atul","103":"amit"}
s=pd.Series(dic)
s

101    shalini sharma
102              atul
103              amit
dtype: object

In [31]:
dic={101:["shalini","sharma",90,89,78],
    102:["amit","verma",89,80,67]
    }
df=pd.DataFrame(dic,index=["fnam","lnam","maths","science","english"])
df.T

        fnam    lnam maths science english
101  shalini  sharma    90      89      78
102     amit   verma    89      80      67

In [34]:
df=pd.read_csv("gapminder.tsv",delimiter="\t")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [35]:
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [37]:
df.tail(5)

       country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [38]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [44]:
dfasia=df[(df["continent"]=="Asia") & (df["year"]<2000)]
dfasia.mean()

C:\Users\admin\AppData\Local\Temp\ipykernel_18696\2117562023.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dfasia.mean()

year         1.974500e+03
lifeExp      5.808165e+01
pop          6.998054e+07
gdpPercap    7.217869e+03
dtype: float64

In [45]:
dfafr=df[(df["continent"]=="Africa") & (df["year"]<2000)]
dfafr.mean()

C:\Users\admin\AppData\Local\Temp\ipykernel_18696\4271779345.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dfafr.mean()

year         1.974500e+03
lifeExp      4.782527e+01
pop          8.508312e+06
gdpPercap    2.063664e+03
dtype: float64

In [46]:
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [48]:
df.loc[[1699,1700,3],["country","pop","gdpPercap"]]

          country       pop   gdpPercap
1699     Zimbabwe   9216418  706.157306
1700     Zimbabwe  10704340  693.420786
3     Afghanistan  11537966  836.197138

In [49]:
df.iloc[[1699,1700,3],[0,3,4]]

          country  lifeExp       pop
1699     Zimbabwe   62.351   9216418
1700     Zimbabwe   60.377  10704340
3     Afghanistan   34.020  11537966