In [9]:
import pandas as pd
data={"name":["shalini","arrav","rama",None],
     "age":[45,34,34,12],
     "salary":[23000,13000,None,24000],
     "date":["2025-02-01","2024-01-01","2025-02-02","2021-03-01"],
     "skill":["low","mid","low","high"]
     }
df=pd.DataFrame(data)
df

      name  age   salary        date skill
0  shalini   45  23000.0  2025-02-01   low
1    arrav   34  13000.0  2024-01-01   mid
2     rama   34      NaN  2025-02-02   low
3     None   12  24000.0  2021-03-01  high

In [7]:
df.sort_values(by="name",ascending=False,na_position="first"
              ,inplace=True)

In [8]:
df

      name  age   salary        date skill
3     None   12  24000.0  2021-03-01  high
0  shalini   45  23000.0  2025-02-01   low
2     rama   56      NaN  2025-02-02   low
1    arrav   34  13000.0  2024-01-01   mid

In [11]:
df.sort_values(by=["age","name"],ascending=[True,False])

      name  age   salary        date skill
3     None   12  24000.0  2021-03-01  high
2     rama   34      NaN  2025-02-02   low
1    arrav   34  13000.0  2024-01-01   mid
0  shalini   45  23000.0  2025-02-01   low

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     4 non-null      int64
 2   salary  3 non-null      float64
 3   date    4 non-null      object
 4   skill   4 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 288.0+ bytes

In [13]:
df["date"]=pd.to_datetime(df["date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     4 non-null      int64
 2   salary  3 non-null      float64
 3   date    4 non-null      datetime64[ns]
 4   skill   4 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 288.0+ bytes

In [14]:
df.sort_values(by="date",ascending=False)

      name  age   salary       date skill
2     rama   34      NaN 2025-02-02   low
0  shalini   45  23000.0 2025-02-01   low
1    arrav   34  13000.0 2024-01-01   mid
3     None   12  24000.0 2021-03-01  high

In [15]:
df.sort_values(by="name",key=lambda x:x.str.len())

      name  age   salary       date skill
2     rama   34      NaN 2025-02-02   low
1    arrav   34  13000.0 2024-01-01   mid
0  shalini   45  23000.0 2025-02-01   low
3     None   12  24000.0 2021-03-01  high

In [17]:
df.nlargest(2,"salary")

      name  age   salary       date skill
3     None   12  24000.0 2021-03-01  high
0  shalini   45  23000.0 2025-02-01   low

In [20]:
order=["low","high","mid"]
df["skill"]=pd.Categorical(df["skill"],categories=order,
                          ordered=True)
df.sort_values(by="skill")

      name  age   salary       date skill
0  shalini   45  23000.0 2025-02-01   low
2     rama   34      NaN 2025-02-02   low
3     None   12  24000.0 2021-03-01  high
1    arrav   34  13000.0 2024-01-01   mid

In [26]:
df.sort_values(by="name").reset_index(drop=True)

      name  age   salary       date skill
0    arrav   34  13000.0 2024-01-01   mid
1     rama   34      NaN 2025-02-02   low
2  shalini   45  23000.0 2025-02-01   low
3     None   12  24000.0 2021-03-01  high

In [27]:
df1=df.sort_values(by=["age","name"])
df1

      name  age   salary       date skill
3     None   12  24000.0 2021-03-01  high
1    arrav   34  13000.0 2024-01-01   mid
2     rama   34      NaN 2025-02-02   low
0  shalini   45  23000.0 2025-02-01   low

In [29]:
df1.sort_index(axis=1)

   age       date     name   salary skill
3   12 2021-03-01     None  24000.0  high
1   34 2024-01-01    arrav  13000.0   mid
2   34 2025-02-02     rama      NaN   low
0   45 2025-02-01  shalini  23000.0   low

In [30]:
cs_df=pd.read_csv("computersales.csv")
cs_df

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
97,98,Michelle Samms,F,46,NY,17-BY3613DX,Laptop,609.99,140.34,Flyer 3,November,2019
98,99,Mick Roberts,M,23,PA,BB980,Desktop,889.99,110.89,Flyer 2,May,2019
99,100,Ed Klondike,M,52,OH,15M-ED0023DX,Laptop,989.99,111.34,Email,November,2019
100,101,Moe Eggert,M,35,PA,GMA4000BST,Desktop,589.99,138.64,Website,May,2019
101,102,Jessica Elk,F,55,PA,AN515-55-53AG,Tablet,669.99,136.69,Flyer 1,December,2019

In [50]:
# mean profit of computer sales
cs_df["Profit"].mean()
# product with highest profit
cs_df.loc[cs_df["Profit"].idxmax(),["Product ID","Contact"]]
# no of people who purchased from WV
cs_df[cs_df["State"]=="WV"]["Sale ID"].count()
# no of purchases in 2019
cs_df[cs_df["Year"]==2019]["Sale ID"].count()
# no of sales for each product type
cs_df["Product ID"].value_counts()
# list of contact of customers who bought specific prd
cs_df[cs_df["Product ID"]=="MY2J2LL"][["Contact","State"]]
# how many people made a website purchase with profit over $150
cs_df[(cs_df["Lead"]=="Website") & (cs_df["Profit"]>150)]["Sale ID"].count()

7

In [58]:
# add and removing cols
data={"name":["shalini sharma","arrav verma","rama"],
     "marks1":[45,34,34],
     "marks2":[23,45,56],
     "date":["2025-02-01","2024-01-01","2025-02-02"],
     "weight":[61,67,74]
     }
df=pd.DataFrame(data)
df

             name  marks1  marks2        date  weight
0  shalini sharma      45      23  2025-02-01      61
1     arrav verma      34      45  2024-01-01      67
2            rama      34      56  2025-02-02      74

In [52]:
df["total"]=df["marks1"]+df["marks2"]
df

      name  marks1  marks2        date  weight  total
0  shalini      45      23  2025-02-01      61     68
1    arrav      34      45  2024-01-01      67     79
2     rama      34      56  2025-02-02      74     90

In [53]:
df.drop(columns=["marks1","marks2"],inplace=True)
df

      name        date  weight  total
0  shalini  2025-02-01      61     68
1    arrav  2024-01-01      67     79
2     rama  2025-02-02      74     90

In [54]:
df["status"]="Active"
df

      name        date  weight  total  status
0  shalini  2025-02-01      61     68  Active
1    arrav  2024-01-01      67     79  Active
2     rama  2025-02-02      74     90  Active

In [55]:
df["weight"]=df["weight"]*2.20
df

      name        date  weight  total  status
0  shalini  2025-02-01   134.2     68  Active
1    arrav  2024-01-01   147.4     79  Active
2     rama  2025-02-02   162.8     90  Active

In [57]:
df["date"]=pd.to_datetime(df["date"])
df["year"]=df["date"].dt.year
df["month"]=df["date"].dt.month
df["day"]=df["date"].dt.day
df

      name       date  weight  total  status  year  month  day
0  shalini 2025-02-01   134.2     68  Active  2025      2    1
1    arrav 2024-01-01   147.4     79  Active  2024      1    1
2     rama 2025-02-02   162.8     90  Active  2025      2    2

In [ ]:
df["name"].str.split(" ",expand=T)